import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/card_context";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Grocery store 📦",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        

    <Link className="fixed bottom-6  md:bottom-7 md:right-6 right-2 z-50 flex flex-col items-center space-y-2 hover:animate-bounce"
      href="/cart"
      rel="noopener noreferrer">
      <span className="hidden md:block cursor-pointer text-base font-bold bg-green-600 hover:bg-green-600 text-gray-100  px-3 py-2 rounded-full transform shadow">
        View Your Cart 📦
        </span>
      </Link>
<CartProvider>
        {children}
        </CartProvider>
      </body>
    </html>
  );

}


